### PR TITLE
Expose Query interface, needed for result pagination

### PR DESCRIPTION
**Pull request by rtfb**
Add WillSwitchPage and PageState to the Iterator, and an entire Query
interface to support it. This allows using gockle for testing result
pagination.

### CODE REVIEW

**Comment by rtfb** [comment]
Hi Will,

I needed this change for the stuff I'm doing, so I went ahead and did that, and it seems to work. Would you be interested in merging that back in?

**Comment by rtfb** [comment]
Ahh, `go vet` complains about `sync.Mutex` being passed by value. I have it fixed on another branch that I intend to submit in another PR. Or I could add another commit here, if you wish.

**Comment by willfaught** [comment]
Hey @rtfb, thanks so much for the PR! It looks excellent overall. I'm so sorry it took so long to respond. I must have missed the GitHub notification emails about it.

**Comment by rtfb** [comment]
No worries, @willfaught, better later than never :-)

**Pull request merged**
